import { useMemo, useState } from 'react'
import { Megaphone, Pencil, Plus, Save, Upload, UserRound } from 'lucide-react'
import { churches } from '../data/churches'

type Person = { id: string; name: string; age: string; gender?: string; phone?: string; address: string; photo?: string; username?: string }
type ChurchData = { committee: Person[]; ydm: Person[]; women: Person[]; pastor: Person; announcements: { id: string; title: string; category: string; content: string; date: string }[] }
const blankPerson = (): Person => ({ id: crypto.randomUUID(), name: '', age: '', gender: '', phone: '', address: '' })
const emptyData = (): ChurchData => ({ committee: [], ydm: [], women: [], pastor: { ...blankPerson() }, announcements: [] })
function readData(id: string): ChurchData { try { return JSON.parse(localStorage.getItem(`church_workspace_${id}`) || JSON.stringify(emptyData())) } catch { return emptyData() } }

export function ChurchAdminPage({ churchId, canManage }: { churchId: string; canManage: boolean }) {
  const church = churches.find(item => item.id === churchId)
  const [data, setData] = useState<ChurchData>(() => readData(churchId))
  const [notice, setNotice] = useState('')
  const [active, setActive] = useState<'committee' | 'ydm' | 'women' | 'pastor' | 'announcements'>('committee')
  const persist = (next: ChurchData) => { setData(next); localStorage.setItem(`church_workspace_${churchId}`, JSON.stringify(next)); setNotice('Saved to this church workspace'); window.setTimeout(() => setNotice(''), 2200) }
  if (!church) return <div className="placeholder panel"><h2>Church workspace unavailable</h2><p>This account is not linked to a church.</p></div>
  return <div className="church-admin-page">
    <div className="page-heading"><div><span className="eyebrow">Private church workspace</span><h1>{church.name}</h1><p className="muted">Manage people, ministries and announcements for this church only.</p></div><div className="church-admin-badge"><span />{canManage ? 'Church Admin' : 'Church Member'}</div></div>
    {notice && <div className="saved-notice" role="status"><Save size={14} />{notice}</div>}
    <div className="church-admin-hero"><div><span className="eyebrow">Access boundary</span><h2>{church.address}</h2><p>Only {church.name} data is available in this workspace.</p></div><div className="church-admin-stat"><strong>{data.committee.length + data.ydm.length + data.women.length + (data.pastor.name ? 1 : 0)}</strong><span>people recorded</span></div></div>
    <div className="church-admin-tabs">{[['committee','Committee'],['ydm','YDM members'],['women','Women ministry'],['pastor','Pastor details'],['announcements','Announcements']].map(([key,label]) => <button className={active === key ? 'active' : ''} key={key} onClick={() => setActive(key as typeof active)}>{label}</button>)}</div>
    {active === 'committee' && <PersonSection title="Committee members" description="Keep the church committee directory current." people={data.committee} canManage={canManage} fields={['phone','address']} onSave={people => persist({ ...data, committee: people })} onCreateAccount={createMemberAccount(church, 'committee')} />}
    {active === 'ydm' && <PersonSection title="YDM members" description="Record the youth ministry members serving this church." people={data.ydm} canManage={canManage} fields={['address']} onSave={people => persist({ ...data, ydm: people })} onCreateAccount={createMemberAccount(church, 'ydm')} />}
    {active === 'women' && <PersonSection title="Women ministry" description="Maintain the women ministry directory." people={data.women} canManage={canManage} fields={['address']} onSave={people => persist({ ...data, women: people })} onCreateAccount={createMemberAccount(church, 'women')} />}
    {active === 'pastor' && <PastorSection pastor={data.pastor} canManage={canManage} onSave={pastor => persist({ ...data, pastor })} />}
    {active === 'announcements' && <AnnouncementSection announcements={data.announcements} canManage={canManage} onSave={announcements => persist({ ...data, announcements })} />}
  </div>
}

function createMemberAccount(church: typeof churches[number], ministry: string) { return async (person: Person) => { if (!person.username) return; const password = window.prompt(`Set a password for ${person.name} (12+ characters)`); if (!password) return; await fetch('/api/accounts', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: person.username, password, role: 'user', section_scope: church.section, church_id: church.id, ministry }) }) } }
function PersonSection({ title, description, people, canManage, fields, onSave, onCreateAccount }: { title: string; description: string; people: Person[]; canManage: boolean; fields: string[]; onSave: (people: Person[]) => void; onCreateAccount: (person: Person) => Promise<void> }) {
  const [editing, setEditing] = useState<Person | null>(null)
  const list = useMemo(() => people, [people])
  const save = () => { if (!editing?.name.trim()) return; const next = list.some(item => item.id === editing.id) ? list.map(item => item.id === editing.id ? editing : item) : [...list, editing]; onSave(next); setEditing(null) }
  return <section className="church-admin-panel panel"><div className="panel-heading"><div><h2>{title}</h2><p>{description}</p></div>{canManage && <button className="primary" onClick={() => setEditing(blankPerson())}><Plus size={15} />Add new</button>}</div>{editing && <PersonForm person={editing} fields={fields} onChange={setEditing} onSave={save} onCancel={() => setEditing(null)} onCreateAccount={onCreateAccount} />}{list.length ? <div className="church-people-list">{list.map(person => <div className="church-person" key={person.id}><div className="church-person-avatar">{person.photo ? <img src={person.photo} alt="" /> : <UserRound size={17} />}</div><div><strong>{person.name}</strong><span>{person.age ? `${person.age} years` : 'Age not added'}{person.gender ? ` · ${person.gender}` : ''}{person.phone ? ` · ${person.phone}` : ''}</span><small>{person.address || 'Address not added'}</small></div>{canManage && <button className="subtle" onClick={() => setEditing(person)}><Pencil size={13} />Edit</button>}</div>)}</div> : <div className="church-empty"><UserRound size={22} /><strong>No members added yet</strong><span>Use Add new to create the first record.</span></div>}</section>
}
function PersonForm({ person, fields, onChange, onSave, onCancel, onCreateAccount }: { person: Person; fields: string[]; onChange: (p: Person) => void; onSave: () => void; onCancel: () => void; onCreateAccount: (p: Person) => Promise<void> }) { const update = (key: keyof Person, value: string) => onChange({ ...person, [key]: value }); return <div className="church-form"><label>Name<input value={person.name} onChange={e => update('name', e.target.value)} /></label><label>Age<input type="number" min="1" max="120" value={person.age} onChange={e => update('age', e.target.value)} /></label><label>Gender<select value={person.gender} onChange={e => update('gender', e.target.value)}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></label>{fields.includes('phone') && <label>Phone number<input type="tel" value={person.phone} onChange={e => update('phone', e.target.value)} /></label>}<label className="wide">Address<input value={person.address} onChange={e => update('address', e.target.value)} /></label><label>Username<input value={person.username || ''} onChange={e => update('username', e.target.value)} placeholder="Optional login" /></label><label className="photo-upload"><span>Photo</span><input type="file" accept="image/*" onChange={e => { const file = e.target.files?.[0]; if (file) { const reader = new FileReader(); reader.onload = () => update('photo', String(reader.result)); reader.readAsDataURL(file) } }} /><Upload size={15} /></label><div className="form-actions"><button className="subtle" onClick={onCancel}>Cancel</button><button className="primary" onClick={() => { onSave(); if (person.username) void onCreateAccount(person) }}><Save size={14} />Save member</button></div></div> }
function PastorSection({ pastor, canManage, onSave }: { pastor: Person; canManage: boolean; onSave: (person: Person) => void }) { const [value, setValue] = useState(pastor); return <section className="church-admin-panel panel"><div className="panel-heading"><div><h2>Pastor details</h2><p>Keep the current pastor profile and photo available to the church team.</p></div></div><div className="pastor-layout"><div className="pastor-photo">{value.photo ? <img src={value.photo} alt="Pastor" /> : <UserRound size={38} />}</div><div className="church-form"><label>Name<input disabled={!canManage} value={value.name} onChange={e => setValue({ ...value, name: e.target.value })} /></label><label>Age<input disabled={!canManage} type="number" value={value.age} onChange={e => setValue({ ...value, age: e.target.value })} /></label><label>Gender<select disabled={!canManage} value={value.gender} onChange={e => setValue({ ...value, gender: e.target.value })}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></label><label className="wide">Address<input disabled={!canManage} value={value.address} onChange={e => setValue({ ...value, address: e.target.value })} /></label>{canManage && <label className="photo-upload wide"><span>Upload pastor photo</span><input type="file" accept="image/*" onChange={e => { const file = e.target.files?.[0]; if (file) { const reader = new FileReader(); reader.onload = () => setValue({ ...value, photo: String(reader.result) }); reader.readAsDataURL(file) } }} /><Upload size={15} /></label>}{canManage && <div className="form-actions wide"><button className="primary" onClick={() => onSave(value)}><Save size={14} />Save pastor details</button></div>}</div></div></section> }
function AnnouncementSection({ announcements, canManage, onSave }: { announcements: ChurchData['announcements']; canManage: boolean; onSave: (items: ChurchData['announcements']) => void }) { const [form, setForm] = useState({ title: '', category: 'General', content: '' }); const add = () => { if (!form.title.trim() || !form.content.trim()) return; onSave([{ ...form, id: crypto.randomUUID(), date: new Date().toISOString() }, ...announcements]); setForm({ title: '', category: 'General', content: '' }) }; return <section className="church-admin-panel panel"><div className="panel-heading"><div><h2>Announcements</h2><p>Publish updates for this church and its ministries.</p></div><Megaphone size={22} color="#d88943" /></div>{canManage && <div className="church-form announcement-form"><label>Title<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}><option>General</option><option>Worship</option><option>YDM</option><option>Women ministry</option><option>Committee</option><option>Urgent</option></select></label><label className="wide">Announcement details<textarea value={form.content} onChange={e => setForm({ ...form, content: e.target.value })} /></label><div className="form-actions wide"><button className="primary" onClick={add}><Megaphone size={14} />Publish announcement</button></div></div>}<div className="announcement-list">{announcements.length ? announcements.map(item => <article key={item.id}><span>{item.category} · {new Date(item.date).toLocaleDateString()}</span><h3>{item.title}</h3><p>{item.content}</p></article>) : <div className="church-empty"><Megaphone size={22} /><strong>No announcements yet</strong><span>Published announcements will appear here.</span></div>}</div></section> }
