import { useState } from 'react'
import { Building2, Church, MapPin, Plus, ShieldCheck, UserRound, Users } from 'lucide-react'
import { churches } from '../data/churches'
import type { Page, Section, UserRole } from '../types'

type AddedRecord = { id: string; name: string; detail: string; section: string; username: string }
type ManagedPage = 'Churches' | 'Users'
function readAdded(page: ManagedPage): AddedRecord[] { try { return JSON.parse(localStorage.getItem(`district_added_${page.toLowerCase()}`) || '[]') } catch { return [] } }

export function WorkspacePage({ page, role, section, sections, onAddSection, onOpenSection }: { page: Page; role: UserRole; section: Section; sections: Section[]; onAddSection: () => void; onOpenSection: (section: Section) => void }) {
  const [adding, setAdding] = useState<ManagedPage | null>(null)
  const [addedChurches, setAddedChurches] = useState<AddedRecord[]>(() => readAdded('Churches'))
  const [addedUsers, setAddedUsers] = useState<AddedRecord[]>(() => readAdded('Users'))
  const visibleChurches = churches.filter((church) => role === 'district' || church.section === section.name)
  const add = () => page === 'Sections' ? onAddSection() : (page === 'Churches' || page === 'Users') && setAdding(page)
  const create = async (record: AddedRecord, password: string) => {
    const response = await fetch('/api/accounts', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: record.username, password, role: adding === 'Churches' ? 'church' : 'user', section_scope: record.section }) })
    if (!response.ok) return false
    const setter = adding === 'Churches' ? setAddedChurches : setAddedUsers
    setter((current) => { const next = [...current, record]; localStorage.setItem(`district_added_${adding?.toLowerCase()}`, JSON.stringify(next)); return next })
    setAdding(null)
    return true
  }
  return <><div className="page-heading"><div><span className="eyebrow">{role === 'district' ? 'District workspace' : `${section.name} workspace`}</span><h1>{page}</h1><p className="muted">Manage {role === 'district' ? 'district-wide' : section.name} data.</p></div>{['Sections', 'Churches', 'Users'].includes(page) && <button className="primary" onClick={add}><Plus size={16} />Add {page.slice(0, -1).toLowerCase()}</button>}</div>{page === 'Sections' ? <SectionDirectory sections={sections} onOpen={onOpenSection} /> : page === 'Churches' ? <ChurchDirectory records={visibleChurches} added={addedChurches} /> : page === 'Users' ? <UserDirectory sections={sections} added={addedUsers} /> : <InfoWorkspace page={page} role={role} section={section} />}{adding && <AddRecordDialog kind={adding} sections={sections} defaultSection={section.name} onClose={() => setAdding(null)} onCreate={create} />}</>
}

function SectionDirectory({ sections, onOpen }: { sections: Section[]; onOpen: (section: Section) => void }) { return <div className="management-grid">{sections.map((item) => <button className="management-card" key={item.name} onClick={() => onOpen(item)}><div className={`management-icon ${item.tone}`}><Building2 size={19} /></div><div><strong>{item.name}</strong><span><MapPin size={12} />{item.town}</span></div><div className="management-meta"><b>{item.churches}</b> churches <b>{item.users}</b> users</div></button>)}</div> }
function ChurchDirectory({ records, added }: { records: typeof churches; added: AddedRecord[] }) { return <div className="management-list panel">{records.map((item) => <div className="management-row" key={item.id}><div className="management-photo"><img src={item.photo} alt="" /></div><div><strong>{item.name}</strong><span>{item.section} · {item.address}</span></div><div className="management-account"><small>Admin login</small><b>{item.username}</b></div></div>)}{added.map((item) => <AddedRow key={item.id} item={item} icon="church" />)}</div> }
function UserDirectory({ sections, added }: { sections: Section[]; added: AddedRecord[] }) { return <div className="management-list panel">{sections.map((item) => <div className="management-row" key={item.admin}><div className="management-avatar"><ShieldCheck size={16} /></div><div><strong>{item.admin}</strong><span>{item.name} Super Admin</span></div><div className="management-account"><small>Scope</small><b>{item.name}</b></div></div>)}{added.map((item) => <AddedRow key={item.id} item={item} icon="user" />)}</div> }
function AddedRow({ item, icon }: { item: AddedRecord; icon: 'church' | 'user' }) { return <div className="management-row"><div className="management-avatar">{icon === 'church' ? <Church size={16} /> : <UserRound size={16} />}</div><div><strong>{item.name}</strong><span>{item.section} · {item.detail}</span></div><div className="management-account"><small>Username</small><b>{item.username}</b></div></div> }

function AddRecordDialog({ kind, sections, defaultSection, onClose, onCreate }: { kind: ManagedPage; sections: Section[]; defaultSection: string; onClose: () => void; onCreate: (record: AddedRecord, password: string) => Promise<boolean> }) {
  const [name, setName] = useState(''), [detail, setDetail] = useState(''), [selectedSection, setSelectedSection] = useState(defaultSection), [username, setUsername] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [saving, setSaving] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!name.trim() || !detail.trim() || !username.trim() || password.length < 12) { setError('Complete all fields and use a password of at least 12 characters.'); return } setSaving(true); const ok = await onCreate({ id: `${kind}-${Date.now()}`, name: name.trim(), detail: detail.trim(), section: selectedSection, username: username.trim() }, password); setSaving(false); if (!ok) setError('Could not save this account. Check your secure session and try again.') }
  return <div className="section-modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="add-record-title"><div className="section-modal add-section-dialog"><button className="section-modal-close" onClick={onClose} aria-label="Close">×</button><span className="eyebrow">District administration</span><h2 id="add-record-title">Add {kind === 'Churches' ? 'church' : 'user'}</h2><p className="modal-town">Create a new {kind === 'Churches' ? 'church and administrator account' : 'user account'}.</p><form onSubmit={submit} noValidate><label>{kind === 'Churches' ? 'Church name' : 'Full name'}<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>{kind === 'Churches' ? 'Address' : 'Role / responsibility'}<input value={detail} onChange={(event) => setDetail(event.target.value)} /></label><label>Section<select value={selectedSection} onChange={(event) => setSelectedSection(event.target.value)}>{sections.map((item) => <option key={item.name}>{item.name}</option>)}</select></label><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /></label>{error && <div className="form-error">{error}</div>}<div className="dialog-actions"><button type="button" className="subtle" onClick={onClose}>Cancel</button><button className="primary" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save'}</button></div></form></div></div>
}
function InfoWorkspace({ page, role, section }: { page: Page; role: UserRole; section: Section }) { const Icon = page === 'Reports' ? Users : ShieldCheck; return <div className="placeholder panel"><div className="placeholder-icon"><Icon size={28} /></div><h2>{page} workspace</h2><p>Your access is limited to {role === 'district' ? 'the district' : section.name}.</p></div> }
