import {useMemo,useState} from'react'
import{createRoot}from'react-dom/client'
import{Activity,ArrowUpRight,Bell,Building2,ChevronDown,Church,ClipboardList,FileText,Gauge,Headphones,LayoutDashboard,LockKeyhole,LogOut,Menu,Plus,Search,ShieldCheck,Users,X}from'lucide-react'
import'./styles.css'
type Page='Overview'|'Sections'|'Churches'|'Users'|'Reports'|'Audit logs'
type Role='district'|'section1'|'section2'|'section3'|'section4'
const sections=[
{name:'Section 1',town:'Nagercoil Central',admin:'section1',churches:18,users:74,tone:'blue',health:96},
{name:'Section 2',town:'Kanyakumari Coast',admin:'section2',churches:14,users:62,tone:'green',health:91},
{name:'Section 3',town:'Thuckalay North',admin:'section3',churches:21,users:87,tone:'orange',health:88},
{name:'Section 4',town:'Marthandam West',admin:'section4',churches:16,users:69,tone:'violet',health:94}]as const
type Section=typeof sections[number]
const accounts:Record<string,Role>={admin:'district',section1:'section1',section2:'section2',section3:'section3',section4:'section4'}
const roleName=(r:Role)=>r==='district'?'District Super Admin':'Section '+r.replace('section','')+' Super Admin'
function Login({login}:{login:(r:Role)=>void}){const[u,setU]=useState('admin'),[p,setP]=useState('admin'),[error,setError]=useState('');function submit(e:React.FormEvent){e.preventDefault();const key=u.trim().toLowerCase(),role=accounts[key];if(role&&p===key)login(role);else setError('The username or password is incorrect.')}return <main className="login-shell"><div className="login-art"><div className="art-copy"><span className="eyebrow">Kanyakumari District</span><h1>One district.<br/><em>Every detail.</em></h1><p>A secure workspace for every district section.</p><div className="art-stat"><ShieldCheck size={18}/>Role-based access</div></div></div><div className="login-panel"><div className="brand"><div className="brand-mark"><Church size={19}/></div>District<span className="brand-accent">OS</span></div><div className="login-form"><span className="eyebrow">Admin portal</span><h2>Welcome back.</h2><p className="muted">Sign in to your assigned workspace.</p><form onSubmit={submit} noValidate><label>Username<input value={u} onChange={e=>setU(e.target.value)}/></label><label>Password<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label>{error&&<div className="form-error">{error}</div>}<button className="primary full">Enter workspace <ArrowUpRight size={17}/></button></form><div className="demo-note"><LockKeyhole size={15}/>District: admin · Sections: section1–section4</div></div></div></main>}
function App(){const[role,setRole]=useState<Role|null>(null),[page,setPage]=useState<Page>('Overview'),[mobile,setMobile]=useState(false),[profile,setProfile]=useState(false),[selected,setSelected]=useState<Section|null>(null);const scoped=useMemo(()=>role==='district'?sections:sections.filter((_,i)=>role==='section'+(i+1)),[role]);if(!role)return <Login login={r=>{setRole(r);setPage('Overview')}}/>;const nav=[['Overview',LayoutDashboard],['Sections',Building2],['Churches',Church],['Users',Users],['Reports',FileText],['Audit logs',ClipboardList]]as const;return <div className="app"><aside className={'sidebar '+(mobile?'open':'')}><div className="side-top"><div className="brand"><div className="brand-mark"><Church size={18}/></div>District<span className="brand-accent">OS</span></div><button className="close-mobile" onClick={()=>setMobile(false)}><X size={18}/></button></div><div className="workspace-switch"><div className="workspace-icon">{role==='district'?'K':role.replace('section','')}</div><div><strong>{role==='district'?'Kanyakumari':scoped[0].name}</strong><small>{role==='district'?'District workspace':'Section workspace'}</small></div><ChevronDown size={15}/></div><nav>{nav.map(([label,Icon])=><button key={label} className={page===label?'active':''} onClick={()=>{setPage(label);setMobile(false)}}><Icon size={17}/>{label}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><Headphones size={17}/><strong>Need a hand?</strong><span>Open the admin guide</span></div><button className="profile" onClick={()=>setRole(null)}><div className="avatar">SA</div><div><strong>{roleName(role)}</strong><small>{role==='district'?'All sections':scoped[0].name}</small></div><LogOut size={15}/></button></div></aside><div className="main"><header><button className="mobile-menu" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="breadcrumb"><span>{role==='district'?'District':scoped[0].name}</span><span>/</span><strong>{page}</strong></div><div className="header-actions"><button className="icon-btn"><Bell size={18}/></button><button className="header-user" onClick={()=>setProfile(!profile)}><div className="avatar">SA</div><span>{roleName(role)}</span><ChevronDown size={14}/></button>{profile&&<div className="profile-menu"><strong>{roleName(role)}</strong><span>{role==='district'?'Full district access':'Access limited to '+scoped[0].name}</span><button className="profile-menu-item">Profile</button><button className="profile-menu-item logout-item" onClick={()=>setRole(null)}>Log out</button></div>}</div></header><main className="content">{page==='Overview'?<Overview role={role} scoped={scoped} open={setSelected} go={setPage}/>:<PageView page={page} role={role} section={scoped[0]}/>}</main></div>{selected&&<Dialog section={selected} close={()=>setSelected(null)}/>}</div>}
function Overview({role,scoped,open,go}:{role:Role,scoped:readonly Section[],open:(s:Section)=>void,go:(p:Page)=>void}){const district=role==='district',churches=scoped.reduce((n,s)=>n+s.churches,0),users=scoped.reduce((n,s)=>n+s.users,0),health=Math.round(scoped.reduce((n,s)=>n+s.health,0)/scoped.length),hour=new Date().getHours(),greeting=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening',date=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date());return <><div className="page-heading"><div><span className="eyebrow">{date}</span><h1>{greeting}, {roleName(role)} <span className="wave">✦</span></h1><p className="muted">{district?'Here is the pulse of your district today.':'Only your assigned section is shown.'}</p></div><button className="primary" onClick={()=>go('Reports')}><FileText size={16}/>View reports</button></div><div className="metrics"><Metric icon={Building2} label="Active sections" value={String(scoped.length)} tone="blue"/><Metric icon={Church} label="Churches" value={String(churches)} tone="green"/><Metric icon={Users} label="People & users" value={String(users)} tone="orange"/><Metric icon={Activity} label="Access health" value={health+'%'} tone="violet"/></div><div className="section-head"><div><h2>{district?'District overview':scoped[0].name+' overview'}</h2><p className="muted">{district?'All four administrative sections.':'This account cannot access other sections.'}</p></div></div><div className="section-grid">{scoped.map(s=><Card key={s.name} s={s} open={open}/>)}{district&&<button className="add-card"><div><Plus size={19}/></div><strong>Add section</strong></button>}</div><div className="bottom-grid"><div className="panel"><h2>Recent activity</h2><div className="activity-list">{['Church records updated','User access granted','Report generated'].map(x=><div className="activity-row" key={x}><div className={'activity-icon '+scoped[0].tone}><ShieldCheck size={16}/></div><div><strong>{x}</strong><span>{scoped[0].name} · Today</span></div></div>)}</div></div><div className="panel"><h2>Access scope</h2><p className="muted">{district?'Read, write, edit and manage all four sections.':'Read, write, edit and manage '+scoped[0].name+' only.'}</p></div></div></>}
function Metric({icon:Icon,label,value,tone}:{icon:React.ElementType,label:string,value:string,tone:string}){return <div className="metric"><div className={'metric-icon '+tone}><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong><small>Within your access</small></div></div>}
function Card({s,open}:{s:Section,open:(s:Section)=>void}){return <button className={'section-card '+s.tone} onClick={()=>open(s)}><div className="card-top"><div className="section-icon"><Church size={20}/></div><span className="status"><i/>Healthy</span></div><h3>{s.name}</h3><p>{s.town}</p><div className="card-stats"><span><Church size={14}/><b>{s.churches}</b> churches</span><span><Users size={14}/><b>{s.users}</b> users</span></div><div className="health"><span>Access health</span><b>{s.health}%</b><div><i style={{width:s.health+'%'}}/></div></div><span className="open-section">Open section <ArrowUpRight size={13}/></span></button>}
function Dialog({section:s,close}:{section:Section,close:()=>void}){return <div className="section-modal-backdrop" role="dialog" aria-modal="true" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="section-modal"><button className="section-modal-close" onClick={close}>×</button><span className="eyebrow">Section workspace</span><h2>{s.name}</h2><p className="modal-town">{s.town}</p><div className="modal-admin"><div className="avatar">SA</div><div><strong>{s.admin}</strong><span>Section super admin · Full section access</span></div></div><div className="modal-metrics"><div><strong>{s.churches}</strong><span>Churches</span></div><div><strong>{s.users}</strong><span>Users</span></div><div><strong>{s.health}%</strong><span>Health</span></div></div></div></div>}
function PageView({page,role,section}:{page:Page,role:Role,section:Section}){return <><div className="page-heading"><div><span className="eyebrow">{role==='district'?'District workspace':section.name+' workspace'}</span><h1>{page}</h1><p className="muted">Manage {role==='district'?'district-wide':section.name} data.</p></div><button className="primary"><Plus size={16}/>Add new</button></div><div className="placeholder panel"><div className="placeholder-icon"><Gauge size={28}/></div><h2>{page} workspace</h2><p>Your access is limited to {role==='district'?'the district':section.name}.</p><button className="subtle"><Search size={15}/>Explore data</button></div></>}
createRoot(document.getElementById('root')!).render(<App/>)
